### ISSUE TITLE
Parse error in string with escapes

### ISSUE THREAD

**Issue by nikomi** [osa1/language-lua#17]
Unfortunately `language-lua` currently fails to parse the file `luaunit.lua` with the following error:
```
lexical error near line: 418 col: 42: Cannot read string "\"\\\\\"\""
```
The offending line is
```
        return '"' .. string.gsub(v,'"', '\\"' ) .. '"'
```
and the offending string is the 2nd parameter to gsub: `'\\"'`.

Workaround: when the string is split into `'\\' .. '"'` parsing works as expected.

The original source file can be found here: https://github.com/bluebird75/luaunit

**Comment by osa1** [comment]
Thanks for reporting. This should now be fixed. I'll address the other issue and then bump version number and upload to Hackage.

**Comment by nikomi** [comment]
Thanx for the quick response!
