### ISSUE TITLE
Use of __GLASGOW_HASKELL__ and MIN_VERSION_ macros

### ISSUE THREAD

**Issue by osa1** [osa1/language-lua#30]
Refactor the code to use `__GLASGOW_HASKELL__` for compiler features and Cabal defined `MIN_VERSION_` for library imports. Currently we use `__GLASGOW_HASKELL__` for importing stuff from base in `PrettyPrinter.hs` and probably in some other files.

**Comment by glguy** [comment]
This is fixed in the release version
