### ISSUE TITLE
Idea: Add a lexer version using ByteString

### ISSUE THREAD

**Issue by nikomi** [osa1/language-lua#33]
Using the appropriate ByteString Alex wrapper this should be achievable with acceptable effort.

Additionally the functions in Language.Lua.StringLiteral would need to be duplicated and the token values (now delivered as ByteString by Alex) would need to be converted to the type(s) used in the syntax tree. Note: this would automatically solve the Alex caveat that long-living tokens should be copied because they share the same lazy ByteString as the input and therefore would prevent the input from being garbage collected.

What do you think?

**Comment by osa1** [comment]
Sounds like a good idea. Would you be willing to implement this?

> Note: this would automatically solve the Alex caveat that long-living tokens should be copied because they share the same lazy ByteString as the input and therefore would prevent the input from being garbage collected.

Where can I learn more about this?

**Comment by nikomi** [comment]
See _5.3.6. The bytestring wrappers_ in https://www.haskell.org/alex/doc/html/wrappers.html

I'll see what I can do regarding an implementation over the holidays.

**Comment by nikomi** [comment]
Not as simple as it seemed...
* Alex does not seem to support _include_ - we would have to duplicate most of the code, increasing both risk and maintenance cost
* language-lua currently does not use any Alex wrapper - so we can't just switch to the corresponding ByteString lexer

Nevertheless I have a version that compiles and successfully passes the unit tests.
* This is a ByteString-only version
* Users wanting to parse Strings must pack them into ByteStrings
* The syntax elements (Name, String, Number, ...) are still Strings, so the required changes are restricted to the Lexer input
* Some optimizations are required - currently this draft version is slightly slower in the benchmark than the original String version. This might be due to the fact we are not using an Alex ByteString wrapper which might be equipped with an optimized Lexer engine

Original version benchmark result:
```
benchmarking Parsing Lua files from 5.3.1 test suite
time                 397.0 ms   (395.0 ms .. 399.3 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 395.1 ms   (394.6 ms .. 395.3 ms)
std dev              410.3 μs   (0.0 s .. 435.4 μs)
variance introduced by outliers: 19% (moderately inflated)
```
Initial ByteString version benchmark result:
```
benchmarking Parsing Lua files from 5.3.1 test suite
time                 424.9 ms   (416.3 ms .. 430.2 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 418.2 ms   (414.3 ms .. 420.6 ms)
std dev              3.650 ms   (0.0 s .. 4.184 ms)
variance introduced by outliers: 19% (moderately inflated)
```

**Comment by osa1** [comment]
Right, so I remember now that I had tried implementing a version that parses ByteString before, and it was also slower. Unfortunately this was years ago and I don't remember much.

Pinging @glguy as he had some performance improvements, maybe he can help.

**Comment by glguy** [comment]
My fork of language-lua gets a speed-up lexing Text instead of String.

https://github.com/glguy/language-lua/tree/happy

**Comment by osa1** [comment]
@glguy shall we merge your Happy-based implementation? Does it have any problems? (failing tests etc.?)

**Comment by glguy** [comment]
I've been using this branch successfully in a work project and the tests all pass. I'd be comfortable with it being merged in. I'm happy to help resolve any issues that might arise.

**Comment by nikomi** [comment]
@glguy: Nice work! The benchmark results are
```
benchmarking Parsing Lua files from 5.3.1 test suite
time                 121.5 ms   (120.4 ms .. 122.6 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 121.0 ms   (120.7 ms .. 121.4 ms)
std dev              499.6 μs   (334.4 μs .. 711.8 μs)
variance introduced by outliers: 11% (moderately inflated)
```
Some minor notes:
* Your ```Name``` type is now ```Text``` - this is a major API change affecting all users of the library and should be reflected in the version number accordingly. (Don't get me wrong, I'm all pro ```Text``` and see no problem in adapting my code - it just affects _all_ users.)
* Lua is completely unaware of things like character set encodings, Lua 5.3 just added module ```utf8``` containing a couple of functions to analyze string values assuming they are encoded in utf-8 - suddenly using Text might have some impact here 
* I would have expected Lazy Text on the input side - but I am sure not everyone would agree with me on this
* My note regarding ByteString tokens values applies to (strict) Text as well: you need to use ```Text.copy``` when extracting token values (e.g. identifiers, numeric/string constants, ...) otherwise they would just be a slice reference forcing the whole (potentially large) script to be kept in memory.
    * See 5.3.6. _The bytestring wrappers_ in https://www.haskell.org/alex/doc/html/wrappers.html for more information.

**Comment by glguy** [comment]
language-lua-0.9.0 is now released with the improved lexer and parser.

Lua isn't completely unaware of character-set encodings as it relies on ASCII encoding to make sense of its input files at the very least. While Text can be decoded from UTF-8, it doesn't have to be. A user who is parsing non-UTF-8 lua source files should use the appropriate function for decoding the input files to Text.

There might be some places that need to use Text.copy.
