### ISSUE TITLE
Improve lexer interface for better error message parsing/printing

### ISSUE THREAD

**Issue by osa1** [osa1/language-lua#9]
Currently lexer is a function with type:

```haskell
llex :: String -> [LTok]
```

This is not very useful for error reporting. We probably need something like:

```haskell
-- | Lexer error at (line, column, character)
type LexerError = (Int, Int, Char)

llex :: String -> Either LexerError [LTok]
```

The problem is that monadic interface of Alex(the type `Alex`) is keeping errors as strings and as far as I can see Alex is not allowing changing the error type(`String`) using the API/standard wrappers.

**Comment by glguy** [comment]
This is fixed in e2c9bc87e4794366129bc4aa8bdf68fe2ccb911d #27
